### ISSUE TITLE
Why don't code section use mono font?

### ISSUE THREAD

**Issue by FOWind** [volcano-sh/website#311]
<img width="598" alt="image" src="https://github.com/volcano-sh/website/assets/13653453/54274ce9-ba2b-4145-b9c6-e064159bf447">

Using sans font:
<img width="1066" alt="image" src="https://github.com/volcano-sh/website/assets/13653453/d903b0af-2bad-4147-a3af-fe268cd0fc9a">

Using mono font
<img width="613" alt="image" src="https://github.com/volcano-sh/website/assets/13653453/e41272ae-93a8-47e7-ae16-f7070dbc75b8">

**Comment by hwdef** [comment]
There's no particular reason for this, and you're welcome to mention pr to fix this if you can
